feat: add Google Slides and Google Forms
sidehustlelab/account-switcher pull request #17
Opened 2022-03-06 13:53 UTC by jaeyongjaykim

This PR closes #15 and closes #16.

Applied formatting and added to handle two services (Slides and Forms)

2022-03-11 03:48 UTC, jaeyongjaykim commented
@anshulahuja98 Would you plase be able to merge this PR and release new version?

2022-03-11 03:49 UTC, anshulahuja98 commented
I had left a pr feedback, can you please address that

2022-04-18 08:53 UTC, anshulahuja98 commented
@jaeyongjaykim  pl address PR feedback so that it can be checked in

2022-04-18 09:01 UTC, jaeyongjaykim commented
> pl address PR feedback so that it can be checked in

I don't see any feedback on this PR. Where would I find that? @anshulahuja98

2022-04-18 09:27 UTC, anshulahuja98 requested changes

2022-04-18 09:27 UTC, anshulahuja98 commented
Seems like I forgot to click submit after the comment
My bad
Can you check now, a comment should show up.

@jaeyongjaykim

2022-04-18 09:43 UTC, jaeyongjaykim commented on background.js
> -    // Google Play Music
![image](https://user-images.githubusercontent.com/14931372/163790312-76dd30bb-61bf-4849-a296-fe89d533100d.png)

> can you please add play music back to this list.
Seems that it got removed.

The reason I've removed Google Play Music is it's no longer serviced, and replaced by YouTube Music. @anshulahuja98

2022-04-18 09:44 UTC, jaeyongjaykim commented
> Can you check now, a comment should show up.

I've commented on your review. @anshulahuja98

2022-04-18 09:52 UTC, anshulahuja98 commented on background.js
> -    // Google Play Music
ah good catch

2022-04-18 09:52 UTC, anshulahuja98 approved these changes

2022-04-18 09:52 UTC, merged

2022-04-18 09:53 UTC, anshulahuja98 commented
Thank you for your contribution @jaeyongjaykim

2022-04-18 09:54 UTC, jaeyongjaykim commented
> Thank you for your contribution

Thank YOU for letting me contribute your beautiful work! @anshulahuja98